-- CreateEnum
CREATE TYPE "UploadStatus" AS ENUM ('Panding', 'InProgress', 'Successful', 'Failed');

-- CreateEnum
CREATE TYPE "PlatformEnum" AS ENUM ('Youtube', 'Facebook', 'X', 'TikTok', 'Instagram');

-- CreateEnum
CREATE TYPE "EventType" AS ENUM ('GENERATE_CLIPS', 'UPLOAD_CLIPS');

-- CreateTable
CREATE TABLE "User" (
    "id" TEXT NOT NULL,
    "username" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "isSuperAdmin" BOOLEAN NOT NULL DEFAULT false,
    "avatar" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "LoginActivity" (
    "id" TEXT NOT NULL,
    "ip" TEXT NOT NULL,
    "device" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "LoginActivity_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Upload" (
    "id" TEXT NOT NULL,
    "uploaderId" TEXT NOT NULL,
    "UploadName" TEXT NOT NULL,
    "uploadDescription" TEXT,
    "uploadDisplayImage" TEXT NOT NULL,
    "videoUrl" TEXT NOT NULL,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT true,
    "autoUpload" BOOLEAN NOT NULL,
    "uploadTimeStamp" TIMESTAMP(3),
    "numberOfClips" INTEGER NOT NULL,
    "groupId" INTEGER NOT NULL,
    "uploadStatus" "UploadStatus" NOT NULL DEFAULT 'Panding',
    "speechLanguage" TEXT NOT NULL DEFAULT 'Hindi',

    CONSTRAINT "Upload_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ClipInfo" (
    "id" TEXT NOT NULL,
    "uploadId" TEXT NOT NULL,
    "clipUrl" TEXT NOT NULL,
    "clipName" TEXT NOT NULL,
    "clipDescription" TEXT NOT NULL,
    "clipTags" TEXT[],
    "isUpload" BOOLEAN NOT NULL DEFAULT false,
    "processingStartedAt" TIMESTAMP(3),
    "processingCompletedAt" TIMESTAMP(3),

    CONSTRAINT "ClipInfo_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SocialAccountGroup" (
    "id" SERIAL NOT NULL,
    "userId" TEXT NOT NULL,
    "groupName" TEXT NOT NULL,
    "groupDescription" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SocialAccountGroup_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FacebookCredential" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "groupId" INTEGER NOT NULL,
    "accessToken" TEXT NOT NULL,
    "pageId" TEXT NOT NULL,
    "pageName" TEXT NOT NULL,

    CONSTRAINT "FacebookCredential_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "InstagramCredential" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "groupId" INTEGER NOT NULL,
    "accessToken" TEXT NOT NULL,
    "businessAccountId" TEXT NOT NULL,
    "accountName" TEXT NOT NULL,

    CONSTRAINT "InstagramCredential_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "YoutubeCredential" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "groupId" INTEGER NOT NULL,
    "channelCustomUrl" TEXT NOT NULL,
    "channelName" TEXT NOT NULL,
    "channelLogo" TEXT NOT NULL,
    "accessToken" TEXT NOT NULL,
    "refreshToken" TEXT,
    "accessTokenExpiry" BIGINT NOT NULL,

    CONSTRAINT "YoutubeCredential_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "XCredential" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "groupId" INTEGER NOT NULL,
    "accessToken" TEXT NOT NULL,
    "accessTokenSecret" TEXT NOT NULL,
    "accountId" TEXT NOT NULL,

    CONSTRAINT "XCredential_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TikTokCredential" (
    "id" SERIAL NOT NULL,
    "userId" TEXT NOT NULL,
    "groupId" INTEGER NOT NULL,
    "accessToken" TEXT NOT NULL,
    "userIdTikTok" TEXT NOT NULL,
    "username" TEXT NOT NULL,
    "clientKey" TEXT,

    CONSTRAINT "TikTokCredential_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Outbox" (
    "id" TEXT NOT NULL,
    "eventType" "EventType" NOT NULL,
    "payload" JSONB NOT NULL,
    "status" "UploadStatus" NOT NULL DEFAULT 'Panding',
    "retryCount" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "processedAt" TIMESTAMP(3)
);

-- CreateIndex
CREATE UNIQUE INDEX "User_id_key" ON "User"("id");

-- CreateIndex
CREATE UNIQUE INDEX "LoginActivity_id_key" ON "LoginActivity"("id");

-- CreateIndex
CREATE UNIQUE INDEX "Upload_UploadName_key" ON "Upload"("UploadName");

-- CreateIndex
CREATE UNIQUE INDEX "SocialAccountGroup_id_key" ON "SocialAccountGroup"("id");

-- CreateIndex
CREATE UNIQUE INDEX "Outbox_id_key" ON "Outbox"("id");

-- AddForeignKey
ALTER TABLE "LoginActivity" ADD CONSTRAINT "LoginActivity_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Upload" ADD CONSTRAINT "Upload_uploaderId_fkey" FOREIGN KEY ("uploaderId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Upload" ADD CONSTRAINT "Upload_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "SocialAccountGroup"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ClipInfo" ADD CONSTRAINT "ClipInfo_uploadId_fkey" FOREIGN KEY ("uploadId") REFERENCES "Upload"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SocialAccountGroup" ADD CONSTRAINT "SocialAccountGroup_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FacebookCredential" ADD CONSTRAINT "FacebookCredential_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FacebookCredential" ADD CONSTRAINT "FacebookCredential_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "SocialAccountGroup"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "InstagramCredential" ADD CONSTRAINT "InstagramCredential_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "InstagramCredential" ADD CONSTRAINT "InstagramCredential_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "SocialAccountGroup"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "YoutubeCredential" ADD CONSTRAINT "YoutubeCredential_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "YoutubeCredential" ADD CONSTRAINT "YoutubeCredential_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "SocialAccountGroup"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "XCredential" ADD CONSTRAINT "XCredential_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "XCredential" ADD CONSTRAINT "XCredential_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "SocialAccountGroup"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TikTokCredential" ADD CONSTRAINT "TikTokCredential_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TikTokCredential" ADD CONSTRAINT "TikTokCredential_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "SocialAccountGroup"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
