import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import RootProvider from "@/components/RootProvider";
import { Toaster } from "@/components/ui/toaster";
const inter = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className={inter.className}
      >
       <RootProvider>
            {children}
         <Toaster/>  
        </RootProvider> 
      </body>
    </html>
  );
}
